SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * BS.SALES) AS SALES
FROM
    AUTHOR A
JOIN
    BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN
    BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE 1=1
AND TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    A.AUTHOR_ID ASC,
    B.CATEGORY DESC;
