WITH MILK AS(
    SELECT
        M.CART_ID
    FROM CART_PRODUCTS M
    WHERE 1=1
    AND M.NAME = ('Milk')
    GROUP BY CART_ID
    )

SELECT
    Y.CART_ID
FROM CART_PRODUCTS Y
INNER JOIN MILK M ON Y.CART_ID = M.CART_ID
WHERE 1=1
AND Y.NAME = ('Yogurt')
GROUP BY Y.CART_ID
ORDER BY Y.CART_ID;