SELECT DISTINCT
    A.USER_ID AS 재구매한회원ID,
    A.PRODUCT_ID AS 재구매한상품ID
FROM ONLINE_SALE A
INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID AND A.SALES_DATE > B.SALES_DATE
ORDER BY A.USER_ID ASC, A.PRODUCT_ID DESC;
