-- 코드를 입력하세요
SELECT
    O.ANIMAL_ID
    ,O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE TO_CHAR(O.DATETIME - I.DATETIME) > 0
ORDER BY (O.DATETIME - I.DATETIME) DESC
FETCH FIRST 2 ROWS ONLY;