-- 코드를 입력하세요
WITH OVER_THREE AS 
(
SELECT WRITER_ID, COUNT(WRITER_ID)
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
)

SELECT
    U.USER_ID
    ,U.NICKNAME
    ,(U.CITY||' '||U.STREET_ADDRESS1||' '||U.STREET_ADDRESS2) AS 전체주소
    ,REGEXP_REPLACE(U.TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3') AS 전화번호
FROM USED_GOODS_USER U
INNER JOIN OVER_THREE O ON U.USER_ID = O.WRITER_ID
ORDER BY U.USER_ID DESC;