-- 코드를 입력하세요
SELECT
    U.USER_ID
    ,U.NICKNAME
    ,(CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2) AS 전체주소
    ,REGEXP_REPLACE(U.TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3') AS 전화번호
FROM USED_GOODS_BOARD B
LEFT JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NICKNAME, CITY, STREET_ADDRESS1, STREET_ADDRESS2, U.TLNO
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY U.USER_ID DESC;