-- 코드를 입력하세요
SELECT
    TO_CHAR(SALES_DATE,'YYYY') AS YEAR
    ,TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS MONTH
    ,GENDER
    ,COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE O
LEFT JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE 1=1
AND GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE,'YYYY'), TO_NUMBER(TO_CHAR(SALES_DATE,'MM')), GENDER
ORDER BY 1,2,3 ASC;