with total2021 as (
    select count(USER_ID) as total
    from USER_INFO
    WHERE EXTRACT(YEAR FROM JOINED) = 2021
)
SELECT EXTRACT(YEAR FROM s.SALES_DATE) as YEAR
      ,EXTRACT(MONTH FROM s.SALES_DATE) as MONTH
      ,COUNT(DISTINCT s.USER_ID) AS PUCHASED_USERS
      ,ROUND(COUNT(DISTINCT s.USER_ID) / (SELECT total 
                                 FROM total2021), 1) AS PURCHASED_RATIO
FROM USER_INFO i
INNER JOIN ONLINE_SALE s ON i.USER_ID = s.USER_ID
WHERE EXTRACT(YEAR FROM i.JOINED) = 2021
GROUP BY EXTRACT(YEAR FROM s.SALES_DATE), EXTRACT(Month FROM s.SALES_DATE)
ORDER BY YEAR, MONTH;