SELECT
    P.PRODUCT_ID
    ,P.PRODUCT_NAME
    ,SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER O
LEFT JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE 1=1
AND TO_CHAR(PRODUCE_DATE,'YYYY-MM') = '2022-05'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY 3 DESC, 1 ASC;