WITH CarRentalCount AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT
    EXTRACT (MONTH FROM A.START_DATE) AS MONTH, A.CAR_ID
    , COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A, CarRentalCount B
WHERE A.CAR_ID = B.CAR_ID
AND A.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
GROUP BY EXTRACT (MONTH FROM A.START_DATE), A.CAR_ID
ORDER BY 1 ASC, 2 DESC;